### ISSUE TITLE
requires base7.2.0.6

### ISSUE THREAD

**Issue by FalseProtagonist** [rmculpepper/racket-zeromq#2]
Hi I'm new to Racket, this seems to always ask for base 7.2.0.6, but I'm guessing it doesn't require that. and I can't work out how to install 7.2.0.6 it always seems to report 7.2 even when you install from https://download.racket-lang.org/releases/7.2/pkgs/base.zip. I got it installed with --deps force, then installed with error unbound identifier unsafe-df->evt

**Comment by rmculpepper** [comment]
I've added a version exception on the package server for 7.2, so if you remove and re-install the package, it should work now.

**Comment by FalseProtagonist** [comment]
Thanks! 

I think maybe it really does require that version of Racket, because it's throwing on unsafe-fd->evt, when I google that I see it in the pull request that you're in here:
https://github.com/racket/racket/pull/2414. 

Is the real solution to for me to somehow install a development version of racket/base (eg. ahead of dwonload.racket, from github)? This is the most popular jupyter-ipython implementation that I can see, is that right? I guess the overlap of racket/jupyter is small since they're all living in Emacs, but it's kind of a bummer if anyone wanting to use Jupyter to learn racket things has to do a slightly advanced install.

**Comment by rmculpepper** [comment]
It looks like you still have the wrong version of the zeromq-r-lib package. What is the output of the following command: `raco pkg show base zeromq-r-lib`?

**Comment by FalseProtagonist** [comment]
I'm really sorry, I hadn't realized that your comment implied that it was *necessary* to reinstall for the package to work, that's stupid of me, it's working now. 

Thanks for your quick response!! Racket up and running in Jupyter!

**Comment by rmculpepper** [comment]
No worries, I'm glad it's working now. Thanks for letting me know about the version problem.
